# ===============
# Header
# ===============
# Navigation menu
menu:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags
  About: /about
# RSS link
rss: /atom.xml
# Path of title banner image of page top
banner: "images/banner.jpg"
# Subtitle of page top
subtitle:
# Header links with icon, specified links will appear at the top right corner of the page
# Each name must correspond to the icon name of Fork Awesome
# https://forkaweso.me/Fork-Awesome/icons/
links:
  github: https://github.com/mooahua
  email: mailto:your_email@example.com

# ===============
# Content
# ===============
# "Read More" link at the bottom of excerpted articles. `false` to hide the link.
excerpt_link: Read More
# Enable fancybox
fancybox: true

# ===============
# Footer
# ===============
# Display copyright notice in footer. Please see https://creativecommons.org/choose/ and https://choosealicense.com/
# You can use html like below.
# copyright: |-
#   <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a></br>
#   All website licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a></br>
copyright:

# ===============
# Sidebar
# ===============
# Sidebar style. You can choose `left`, `right`, `bottom` or `false`.
sidebar: right
# Widgets displaying in sidebar
widgets:
- about
- category
- tag
- tagcloud
- archive
- recent_posts

# ===============
# 个人简介
# ===============
about:
  avatar: /images/avatar.png
  name: 混世阿华
  description: 一个热爱技术与生活的开发者，记录学习心得与生活感悟。

# ===============
# Widget behavior
# ===============
archive_type: 'monthly'
show_count: false
# How many posts display in Home page.
recent_posts_limits: 5

# ===============
# Miscellaneous
# ===============
google_analytics: your_google_analytics_tracking_id
gauges_analytics:
# Favicon path
favicon: /favicon.png
# Twitter ID
twitter:
fb_admins:
fb_app_id:

# ===============
# Comment system
# ===============
# Disqus comment system.
disqus_shortname:
# valine comment system. https://valine.js.org
valine:
  enable: true
  appId: your_app_id
  appKey: your_app_key
  notify: false
  verify: false
  pageSize: 10
  avatar: mm
  lang: zh-cn
  placeholder: 请留下你的足迹 ~
  guest_info: nick,mail,link
